# Generated by Django 4.2.1 on 2023-06-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_type_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.FileField(null=True, upload_to='static', verbose_name='Oyun Resmi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Ürün adı'),
        ),
    ]
