# Generated by Django 4.2.1 on 2023-06-26 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0005_category_img_alter_product_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Oyuncu Adı')),
                ('text', models.TextField(verbose_name='İçerik')),
                ('image', models.FileField(upload_to='product', verbose_name='Ürün Resmi')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Fiyat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı - Satıcı')),
            ],
        ),
    ]
