# Generated by Django 4.2.1 on 2023-06-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_player_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='video_link',
        ),
        migrations.AddField(
            model_name='player',
            name='video_embed',
            field=models.TextField(blank=True, null=True, verbose_name='Video Embed Kodu'),
        ),
    ]
