# Generated by Django 4.2.1 on 2023-06-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_remove_player_video_link_player_video_embed'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='video_embed',
            field=models.TextField(blank=True, null=True, verbose_name='Video Embed Kodu'),
        ),
    ]
