# Generated by Django 4.2.1 on 2023-07-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_shoping'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='stok',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='Stok'),
        ),
    ]
