# Generated by Django 4.2.1 on 2023-07-05 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paymentDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shoping',
            name='paymentCheck',
            field=models.BooleanField(default=False, verbose_name='Ödeme yapıldı mı?'),
        ),
    ]
