# Generated by Django 4.2.1 on 2023-07-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_payment_paymentdate_shoping_paymentcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='products',
            field=models.ManyToManyField(to='market.shoping'),
        ),
    ]
