# Generated by Django 4.2.1 on 2023-07-14 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_alter_payment_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Ürün', 'verbose_name_plural': 'Ürünler'},
        ),
    ]
