# Generated by Django 4.2.1 on 2023-07-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paymentCheck',
            field=models.BooleanField(default=False, verbose_name='Ödeme yapıldı mı?'),
        ),
    ]
