# Generated by Django 4.2.1 on 2023-06-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinfo_img_userinfo_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='img',
        ),
    ]
