# Generated by Django 4.2.1 on 2023-07-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_userinfo_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='img',
            field=models.ImageField(null=True, upload_to='profile', verbose_name='Profil Resmi'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=50, null=True, verbose_name='Şifre'),
        ),
    ]
