# Generated by Django 4.2.1 on 2023-07-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userinfo_user_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='img',
        ),
    ]
