# Generated by Django 4.2.1 on 2023-07-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_userinfo_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='img',
            field=models.ImageField(null=True, upload_to='profile', verbose_name='Profil Resmi'),
        ),
    ]
