# Generated by Django 4.2.1 on 2023-07-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userinfo_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='img',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Şifre'),
        ),
    ]
