# Generated by Django 4.2.1 on 2023-07-15 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_userinfo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': 'Kullanıcı Bilgileri'},
        ),
    ]
